README: add details about the .env configuration
If the .env file doesn't exist, the docker-compose build will fail with this command:
ERROR: Couldn't find env file: response/.env

Fix #16